spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 2
      max-lifetime: 1800000
      idle-timeout: 30000

  webflux:
    base-path: /api/v1

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/ecommerce
    user: postgres
    password: postgres
    locations: classpath:db/migration
    
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

logging:
  level:
    root: INFO
    '[org.springframework]': INFO
    '[learn.ai.ecommerce]': DEBUG

server:
  port: 8080
